package citi.scorecard;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ScoreCardData implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int segmentId;
   private double segmentConstant;
   private java.lang.String formula;
   private double missValue;
   private double minValue;
   private double maxValue;
   private java.lang.String transx;
   private double coef;
   private int reason;
   private double mean;

   public ScoreCardData()
   {
   }

   public int getSegmentId()
   {
      return this.segmentId;
   }

   public void setSegmentId(int segmentId)
   {
      this.segmentId = segmentId;
   }

   public double getSegmentConstant()
   {
      return this.segmentConstant;
   }

   public void setSegmentConstant(double segmentConstant)
   {
      this.segmentConstant = segmentConstant;
   }

   public java.lang.String getFormula()
   {
      return this.formula;
   }

   public void setFormula(java.lang.String formula)
   {
      this.formula = formula;
   }

   public double getMissValue()
   {
      return this.missValue;
   }

   public void setMissValue(double missValue)
   {
      this.missValue = missValue;
   }

   public double getMinValue()
   {
      return this.minValue;
   }

   public void setMinValue(double minValue)
   {
      this.minValue = minValue;
   }

   public double getMaxValue()
   {
      return this.maxValue;
   }

   public void setMaxValue(double maxValue)
   {
      this.maxValue = maxValue;
   }

   public java.lang.String getTransx()
   {
      return this.transx;
   }

   public void setTransx(java.lang.String transx)
   {
      this.transx = transx;
   }

   public double getCoef()
   {
      return this.coef;
   }

   public void setCoef(double coef)
   {
      this.coef = coef;
   }

   public int getReason()
   {
      return this.reason;
   }

   public void setReason(int reason)
   {
      this.reason = reason;
   }

   public double getMean()
   {
      return this.mean;
   }

   public void setMean(double mean)
   {
      this.mean = mean;
   }

   public ScoreCardData(int segmentId, double segmentConstant,
         java.lang.String formula, double missValue, double minValue,
         double maxValue, java.lang.String transx, double coef, int reason,
         double mean)
   {
      this.segmentId = segmentId;
      this.segmentConstant = segmentConstant;
      this.formula = formula;
      this.missValue = missValue;
      this.minValue = minValue;
      this.maxValue = maxValue;
      this.transx = transx;
      this.coef = coef;
      this.reason = reason;
      this.mean = mean;
   }
@Override
	public String toString() {
		return "ScoreCardData [segmentId=" + segmentId + ", segmentConstant=" + segmentConstant + ", formula=" + formula
				+ ", missValue=" + missValue + ", minValue=" + minValue + ", maxValue=" + maxValue + ", transx="
				+ transx + ", coef=" + coef + ", reason=" + reason + ", mean=" + mean + "]";
	}
}