package citi.scorecard;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ScoreFormula implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String key;
   private double value;

   public ScoreFormula()
   {
   }

   public java.lang.String getKey()
   {
      return this.key;
   }

   public void setKey(java.lang.String key)
   {
      this.key = key;
   }

   public double getValue()
   {
      return this.value;
   }

   public void setValue(double value)
   {
      this.value = value;
   }

   public ScoreFormula(java.lang.String key, double value)
   {
      this.key = key;
      this.value = value;
   }
    @Override
	public String toString() {
		return "ScoreFormula [key=" + key + ", value=" + value + "]";
	}
}