package citi.scorecard;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ScoreCardDataTable implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int segmentId;
   private int noOfFormula;

   public ScoreCardDataTable()
   {
   }

   public int getSegmentId()
   {
      return this.segmentId;
   }

   public void setSegmentId(int segmentId)
   {
      this.segmentId = segmentId;
   }

   public int getNoOfFormula()
   {
      return this.noOfFormula;
   }

   public void setNoOfFormula(int noOfFormula)
   {
      this.noOfFormula = noOfFormula;
   }

   public ScoreCardDataTable(int segmentId, int noOfFormula)
   {
      this.segmentId = segmentId;
      this.noOfFormula = noOfFormula;
   }

}