package citi.scorecard;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SegmentConsant implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int segmentId;
   private double segmentConstant;

   public SegmentConsant()
   {
   }

   public int getSegmentId()
   {
      return this.segmentId;
   }

   public void setSegmentId(int segmentId)
   {
      this.segmentId = segmentId;
   }

   public double getSegmentConstant()
   {
      return this.segmentConstant;
   }

   public void setSegmentConstant(double segmentConstant)
   {
      this.segmentConstant = segmentConstant;
   }

   public SegmentConsant(int segmentId, double segmentConstant)
   {
      this.segmentId = segmentId;
      this.segmentConstant = segmentConstant;
   }
@Override
	public String toString() {
		return "SegmentConsant [segmentConstant=" + segmentConstant + ", segmentId=" + segmentId + "]";
	}

}